[package]
name = "gm_zip"
authors = ["Earu"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gmod = { version = "*", default-features = false, features = ["gmcl"] }
zip = "0.5.13"
glob = "0.3.0"